package com.browntowndev.pocketcrew.domain.usecase.modelconfig

import com.browntowndev.pocketcrew.domain.model.config.LocalModelAsset
import com.browntowndev.pocketcrew.domain.model.config.LocalModelConfiguration
import com.browntowndev.pocketcrew.domain.model.config.LocalModelConfigurationId
import com.browntowndev.pocketcrew.domain.model.config.SlotResolvedLocalModel
import com.browntowndev.pocketcrew.domain.model.inference.ModelType
import com.browntowndev.pocketcrew.domain.port.inference.LoggingPort
import com.browntowndev.pocketcrew.domain.port.repository.DefaultModelRepositoryPort
import com.browntowndev.pocketcrew.domain.port.repository.LocalModelRepositoryPort
import com.browntowndev.pocketcrew.domain.port.repository.TransactionProvider
import javax.inject.Inject

class SyncLocalModelRegistryUseCase @Inject constructor(
    private val localModelRepository: LocalModelRepositoryPort,
    private val defaultModelRepository: DefaultModelRepositoryPort,
    private val transactionProvider: TransactionProvider,
    private val logger: LoggingPort
) {
    /**
     * Syncs a local model asset to the registry.
     * 
     * Uses the configId from the LocalModelConfiguration as the authoritative ID.
     * If a config with the same configId exists, it will be updated; otherwise a new config is created.
     * 
     * @param modelType The model type slot (VISION, DRAFT_ONE, etc.)
     * @param asset The local model asset to sync
     * @return SlotResolvedLocalModel containing the synced asset and configuration
     */
    suspend operator fun invoke(
        modelType: ModelType,
        asset: LocalModelAsset
    ): SlotResolvedLocalModel {
        return transactionProvider.runInTransaction {
            val assetId = localModelRepository.upsertLocalAsset(asset)
            val primaryConfig = asset.configurations.firstOrNull()
                ?: throw IllegalArgumentException("Asset must contain at least one configuration")
            
            // Use the configId from the config as the authoritative ID
            // If configId is empty (user-created config), let the repository generate one
            val configId = if (primaryConfig.id.value.isNotEmpty()) {
                primaryConfig.id
            } else {
                null // Will be generated by upsertLocalConfiguration
            }
            
            // Check if there is an existing assignment for this model type
            val existingAssignment = defaultModelRepository.getDefault(modelType)
            
            // Determine the config ID to use:
            // 1. If existing assignment references the same config, reuse it
            // 2. Otherwise use the configId from the primary config (or null to generate new)
            val finalConfigId = when {
                existingAssignment?.localConfigId != null && configId == null -> {
                    // Existing assignment but new user config - generate new ID
                    null
                }
                existingAssignment?.localConfigId == configId -> {
                    // Same config ID as existing assignment - reuse it
                    existingAssignment?.localConfigId
                }
                else -> {
                    // Use the configId from the primary config (may be null to generate new)
                    configId
                }
            }
            
            val configToPersist = primaryConfig.copy(
                id = finalConfigId ?: LocalModelConfigurationId(""),
                localModelId = assetId
            )
            
            logger.debug(
                "SyncLocalModelRegistryUseCase",
                "syncLocalModelRegistry($modelType): assetId=$assetId sha=${asset.metadata.sha256} " +
                    "file=${asset.metadata.localFileName} preset=${primaryConfig.displayName} " +
                    "thinking=${primaryConfig.thinkingEnabled} configId=${finalConfigId?.value ?: "NEW"}"
            )
            
            val persistedConfigId = localModelRepository.upsertLocalConfiguration(configToPersist)
            
            if (existingAssignment == null) {
                defaultModelRepository.setDefault(modelType, localConfigId = persistedConfigId, apiConfigId = null)
            }
            
            val finalAsset = localModelRepository.getAssetById(assetId)
                ?: throw IllegalStateException("Failed to load asset after activation")
            val finalConfig = finalAsset.configurations.find { it.id == persistedConfigId }
                ?: throw IllegalStateException("Failed to load config after activation")
                
            SlotResolvedLocalModel(modelType, finalAsset, finalConfig)
        }
    }
}
