package com.browntowndev.pocketcrew.domain.port.repository

import com.browntowndev.pocketcrew.domain.model.chat.Chat
import com.browntowndev.pocketcrew.domain.model.chat.ThinkingData
import com.browntowndev.pocketcrew.domain.model.inference.ModelType
import com.browntowndev.pocketcrew.domain.model.inference.PipelineStep

/**
 * Port (interface) for chat persistence.
 * Implemented by the data layer.
 *
 * Note: This repository handles saving chats to the chat table.
 * Transaction management is delegated to the use case layer to keep
 * this interface agnostic of transaction lifecycle.
 */
interface ChatRepository {
    /**
     * Creates a new chat in the database.
     *
     * @param chat The chat to create
     * @return The ID of the newly created chat
     */
    suspend fun createChat(chat: Chat): Long

    /**
     * Saves an assistant message to the database.
     *
     * @param messageId The ID of the message
     * @param content The content of the message
     * @param thinkingData Optional thinking data for reasoning models
     */
    suspend fun saveAssistantMessage(
        messageId: Long,
        content: String,
        thinkingData: ThinkingData? = null
    )

    /**
     * Saves a single step completion for Crew mode.
     * Called after each step finishes to persist step output for display and rehydration.
     *
     * @param messageId The ID of the assistant message this step belongs to
     * @param stepName The display name of the step (e.g., "Draft One", "Draft Two")
     * @param stepOutput The output generated by this step
     * @param thinkingDurationSeconds How long this step took
     * @param thinkingSteps The thinking steps from this step
     * @param modelDisplayName The display name of the model used
     * @param stepOrder The order of this step (0 = first step)
     *                     stepType is derived from stepOrder in the domain model
     */
    suspend fun saveStepCompletion(
        messageId: Long,
        stepType: PipelineStep,
        stepOutput: String,
        thinkingDurationSeconds: Int,
        thinkingSteps: List<String>,
        modelType: ModelType
    )

    /**
     * Loads all step completions for a message.
     * Used during chat rehydration to restore step completion state.
     *
     * @param messageId The ID of the assistant message
     * @return List of step completion data, ordered by stepOrder
     */
    suspend fun getStepCompletionsForMessage(messageId: Long): List<StepCompletionData>
}

/**
 * Data class for step completion information.
 * Used for persistence and transfer between layers.
 * Display names are derived from stepType and modelType at runtime via ModelRegistry.
 */
data class StepCompletionData(
    val stepOutput: String,
    val thinkingDurationSeconds: Int,
    val totalDurationSeconds: Int = 0,  // Total time (for BottomSheet)
    val thinkingSteps: List<String>,
    val stepType: PipelineStep,
    val modelType: ModelType
)
